name: build_project

on:
  pull_request:
    branches: [ main ]

jobs:
 build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.13
    - name: Install dependencies
      run: |
        cd client
        npm install
